# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


>list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

>tolist() 才能達成多層的型態轉換。

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:
a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[7 1 3 3 1 2]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[3 7 7 7]
 [5 1 4 9]
 [3 7 4 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[9 1]
  [7 9]
  [3 1]]

 [[9 1]
  [9 0]
  [2 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[1, 4, 5, 7, 5, 3]
[1, 4, 5, 7, 5, 3]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 6, 5, 5], [4, 6, 6, 2], [0, 3, 2, 4]]
[array([3, 6, 5, 5]), array([4, 6, 6, 2]), array([0, 3, 2, 4])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[6, 6], [0, 0], [1, 9]], [[7, 8], [7, 6], [4, 3]]]
[array([[6, 6],
       [0, 0],
       [1, 9]]), array([[7, 8],
       [7, 6],
       [4, 3]])]


In [8]:
def tolist(iterable):
    x = iterable.tolist()
    return x

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 4, 5, 7, 5, 3]
[[3, 6, 5, 5], [4, 6, 6, 2], [0, 3, 2, 4]]
[[[6, 6], [0, 0], [1, 9]], [[7, 8], [7, 6], [4, 3]]]
