# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


>zeros() 函式，可以依照傳入的形狀引數，建立元素全為 0 的陣列。

>empty() 函式不需要給定起始值，可以建立給定形狀的陣列，元素值會隨機給定。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
# 參考解答

a = np.random.rand(2, 3)

a = a * 100

a

array([[92.66067067, 36.44756315, 76.35400829],
       [13.46057385, 11.95887563, 86.48599647]])

In [3]:
a.round()

array([[93., 36., 76.],
       [13., 12., 86.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [4]:
a = np.random.rand(2, 3)

m = 20
n = 40

a = a * (n - m) + m

a.round()

array([[28., 39., 29.],
       [33., 23., 32.]])